spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bumawiki?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:

  logging:
    level:
      org:
        hibernate:
          SQL: debug

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
    format_sql: true

  profiles:
    include: oauth

  redis:
    host: localhost
    port: 6379